### ISSUE TITLE
Conda/mamba installation appears to be broken

### ISSUE THREAD

**Issue by tfenne** [mmcguffi/pLannotate#22]
Installed via conda as per the instructions in the README:

```
mamba create -n plannotate -c conda-forge -c bioconda plannotate
```

which resulted in version 1.2.0 being installed.  I then (after failing with my own plasmids) downloaded `pUC19.fa` from the data directory in this github repo, and tried annotating it and this is what I get:

```
(plannotate) fennell@x86_64 /tmp $ plannotate batch --input pUC19.fa --html --output /tmp
2023-04-07 09:15:03.772
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run /Users/fennell/conda.x86/envs/plannotate/bin/plannotate [ARGUMENTS]
Traceback (most recent call last):
  File "/Users/fennell/conda.x86/envs/plannotate/bin/plannotate", line 10, in <module>
    sys.exit(main())
  File "/Users/fennell/conda.x86/envs/plannotate/lib/python3.10/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/fennell/conda.x86/envs/plannotate/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/fennell/conda.x86/envs/plannotate/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/fennell/conda.x86/envs/plannotate/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/fennell/conda.x86/envs/plannotate/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/fennell/conda.x86/envs/plannotate/lib/python3.10/site-packages/plannotate/pLannotate.py", line 116, in main_batch
    recordDf = annotate(inSeq, yaml_file, linear, detailed)
  File "/Users/fennell/conda.x86/envs/plannotate/lib/python3.10/site-packages/plannotate/annotate.py", line 355, in annotate
    blastDf = clean(blastDf)
  File "/Users/fennell/conda.x86/envs/plannotate/lib/python3.10/site-packages/plannotate/annotate.py", line 178, in clean
    rowSlice = (seqSpace[columnSlice] == kind).any(1) #only the rows that are in the columns of hit
TypeError: NDFrame._add_numeric_operations.<locals>.any() takes 1 positional argument but 2 were given
```

**Comment by mmcguffi** [comment]
Thanks for the information and sorry for the hassle. Im not immediately sure what is going on here -- could you give me the the output of `conda list` in your plannotate env?

**Comment by tfenne** [comment]
Here's the list:

```
# packages in environment at /Users/fennell/conda.x86/envs/plannotate:
#
# Name                    Version                   Build  Channel
altair                    4.2.2              pyhd8ed1ab_0    conda-forge
appnope                   0.1.3              pyhd8ed1ab_0    conda-forge
arrow-cpp                 11.0.0          h694c41f_13_cpu    conda-forge
astor                     0.8.1              pyh9f0ad1d_0    conda-forge
asttokens                 2.2.1              pyhd8ed1ab_0    conda-forge
attrs                     22.2.0             pyh71513ae_0    conda-forge
aws-c-auth                0.6.26               hcaaecf5_1    conda-forge
aws-c-cal                 0.5.21               hf54dd2f_2    conda-forge
aws-c-common              0.8.14               hb7f2c08_0    conda-forge
aws-c-compression         0.2.16               h99c63db_5    conda-forge
aws-c-event-stream        0.2.20               h0ae4c0f_4    conda-forge
aws-c-http                0.7.6                hcdd7835_0    conda-forge
aws-c-io                  0.13.19              had634fe_3    conda-forge
aws-c-mqtt                0.8.6               ha4e05e3_12    conda-forge
aws-c-s3                  0.2.7                hba8c00c_1    conda-forge
aws-c-sdkutils            0.1.8                h99c63db_0    conda-forge
aws-checksums             0.1.14               h99c63db_5    conda-forge
aws-crt-cpp               0.19.8              h8b21dc2_12    conda-forge
aws-sdk-cpp               1.10.57              h0d082ec_8    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
base58                    2.1.1              pyhd8ed1ab_0    conda-forge
biopython                 1.81            py310h90acd4f_0    conda-forge
blast                     2.12.0               h0370960_3    bioconda
blinker                   1.6                pyhd8ed1ab_0    conda-forge
bokeh                     2.4.1           py310h2ec42d9_2    conda-forge
boto3                     1.26.108           pyhd8ed1ab_0    conda-forge
botocore                  1.29.108           pyhd8ed1ab_0    conda-forge
brotlipy                  0.7.0           py310h90acd4f_1005    conda-forge
bzip2                     1.0.8                h0d85af4_4    conda-forge
c-ares                    1.18.1               h0d85af4_0    conda-forge
ca-certificates           2022.12.7            h033912b_0    conda-forge
cachetools                5.3.0              pyhd8ed1ab_0    conda-forge
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py310ha78151a_3    conda-forge
charset-normalizer        3.1.0              pyhd8ed1ab_0    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
comm                      0.1.3              pyhd8ed1ab_0    conda-forge
cryptography              40.0.1          py310hdd0c95c_0    conda-forge
curl                      7.88.1               h6df9250_1    conda-forge
debugpy                   1.6.7           py310h7a76584_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
diamond                   2.1.6                hb655df1_0    bioconda
entrez-direct             16.2                 h193322a_1    bioconda
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
executing                 1.2.0              pyhd8ed1ab_0    conda-forge
freetype                  2.12.1               h3f81eb7_1    conda-forge
gettext                   0.21.1               h8a4c099_0    conda-forge
gflags                    2.2.2             hb1e8313_1004    conda-forge
gitdb                     4.0.10             pyhd8ed1ab_0    conda-forge
gitpython                 3.1.31             pyhd8ed1ab_0    conda-forge
glog                      0.6.0                h8ac2a54_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
importlib-metadata        6.1.0              pyha770c72_0    conda-forge
importlib_metadata        6.1.0                hd8ed1ab_0    conda-forge
importlib_resources       5.12.0             pyhd8ed1ab_0    conda-forge
infernal                  1.1.4           pl5321ha5712d3_1    bioconda
ipykernel                 6.22.0             pyh736e0ef_0    conda-forge
ipython                   8.12.0             pyhd1c38e8_0    conda-forge
ipywidgets                8.0.6              pyhd8ed1ab_0    conda-forge
jedi                      0.18.2             pyhd8ed1ab_0    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
jmespath                  1.0.1              pyhd8ed1ab_0    conda-forge
jsonschema                4.17.3             pyhd8ed1ab_0    conda-forge
jupyter_client            8.1.0              pyhd8ed1ab_0    conda-forge
jupyter_core              5.3.0           py310h2ec42d9_0    conda-forge
jupyterlab_widgets        3.0.7              pyhd8ed1ab_0    conda-forge
krb5                      1.20.1               h049b76e_0    conda-forge
lcms2                     2.15                 h2dcdeff_1    conda-forge
lerc                      4.0.0                hb486fe8_0    conda-forge
libabseil                 20230125.0      cxx17_hf0c8a7f_1    conda-forge
libarrow                  11.0.0          h547aefa_13_cpu    conda-forge
libblas                   3.9.0           16_osx64_openblas    conda-forge
libbrotlicommon           1.0.9                hb7f2c08_8    conda-forge
libbrotlidec              1.0.9                hb7f2c08_8    conda-forge
libbrotlienc              1.0.9                hb7f2c08_8    conda-forge
libcblas                  3.9.0           16_osx64_openblas    conda-forge
libcrc32c                 1.1.2                he49afe7_0    conda-forge
libcurl                   7.88.1               h6df9250_1    conda-forge
libcxx                    16.0.1               h71dddab_0    conda-forge
libdeflate                1.18                 hac1461d_0    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 haf1e3a3_1    conda-forge
libevent                  2.1.10               h7d65743_4    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libgfortran               5.0.0           11_3_0_h97931a8_31    conda-forge
libgfortran5              12.2.0              he409387_31    conda-forge
libgoogle-cloud           2.8.0                h176059f_1    conda-forge
libgrpc                   1.52.1               h5bc3d57_1    conda-forge
libiconv                  1.17                 hac89ed1_0    conda-forge
libidn2                   2.3.4                hb7f2c08_0    conda-forge
libjpeg-turbo             2.1.5.1              hb7f2c08_0    conda-forge
liblapack                 3.9.0           16_osx64_openblas    conda-forge
libnghttp2                1.52.0               he2ab024_0    conda-forge
libopenblas               0.3.21          openmp_h429af6e_3    conda-forge
libpng                    1.6.39               ha978bb4_0    conda-forge
libprotobuf               3.21.12              hbc0c0cd_0    conda-forge
libsodium                 1.0.18               hbcb3906_1    conda-forge
libsqlite                 3.40.0               ha978bb4_0    conda-forge
libssh2                   1.10.0               h47af595_3    conda-forge
libthrift                 0.18.1               h16802d8_0    conda-forge
libtiff                   4.5.0                hedf67fa_6    conda-forge
libunistring              0.9.10               h0d85af4_0    conda-forge
libutf8proc               2.8.0                hb7f2c08_0    conda-forge
libwebp-base              1.3.0                hb7f2c08_0    conda-forge
libxcb                    1.13              h0d85af4_1004    conda-forge
libzlib                   1.2.13               hfd90126_4    conda-forge
llvm-openmp               16.0.1               h61d9ccf_0    conda-forge
lz4-c                     1.9.4                hf0c8a7f_0    conda-forge
markupsafe                2.1.2           py310h90acd4f_0    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
ncurses                   6.3                  h96cf925_1    conda-forge
nest-asyncio              1.5.6              pyhd8ed1ab_0    conda-forge
numpy                     1.24.2          py310h788a5b3_0    conda-forge
openjpeg                  2.5.0                h13ac156_2    conda-forge
openssl                   3.1.0                hfd90126_0    conda-forge
orc                       1.8.3                ha9d861c_0    conda-forge
packaging                 23.0               pyhd8ed1ab_0    conda-forge
pandas                    2.0.0           py310hecf8f37_0    conda-forge
parquet-cpp               1.5.1                         2    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 he49afe7_0    conda-forge
perl                      5.32.1          2_h0d85af4_perl5    conda-forge
perl-archive-tar          2.40            pl5321hdfd78af_0    bioconda
perl-carp                 1.50            pl5321hd8ed1ab_0    conda-forge
perl-common-sense         3.75            pl5321hd8ed1ab_0    conda-forge
perl-compress-raw-bzip2   2.201           pl5321h775f41a_0    conda-forge
perl-compress-raw-zlib    2.202           pl5321h775f41a_0    conda-forge
perl-encode               3.19            pl5321hb7f2c08_0    conda-forge
perl-exporter             5.74            pl5321hd8ed1ab_0    conda-forge
perl-exporter-tiny        1.002002        pl5321hd8ed1ab_0    conda-forge
perl-extutils-makemaker   7.70            pl5321hd8ed1ab_0    conda-forge
perl-io-compress          2.201           pl5321h9722bc1_0    bioconda
perl-io-zlib              1.14            pl5321hdfd78af_0    bioconda
perl-json                 4.10            pl5321hdfd78af_0    bioconda
perl-json-xs              2.34            pl5321hcd10b59_5    bioconda
perl-list-moreutils       0.430           pl5321hdfd78af_0    bioconda
perl-list-moreutils-xs    0.430           pl5321ha5712d3_1    bioconda
perl-parent               0.241           pl5321hd8ed1ab_0    conda-forge
perl-pathtools            3.75            pl5321h775f41a_0    conda-forge
perl-scalar-list-utils    1.63            pl5321h775f41a_0    conda-forge
perl-storable             3.15            pl5321h775f41a_0    conda-forge
perl-types-serialiser     1.01            pl5321hdfd78af_0    bioconda
pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.5.0           py310h6b2f720_0    conda-forge
pip                       23.0.1             pyhd8ed1ab_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
plannotate                1.2.0              pyhdfd78af_3    bioconda
platformdirs              3.2.0              pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.38             pyha770c72_0    conda-forge
prompt_toolkit            3.0.38               hd8ed1ab_0    conda-forge
protobuf                  4.21.12         py310h7a76584_0    conda-forge
psutil                    5.9.4           py310h90acd4f_0    conda-forge
pthread-stubs             0.4               hc929b4f_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pyarrow                   11.0.0          py310h435aefc_13_cpu    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydeck                    0.8.0              pyhd8ed1ab_0    conda-forge
pygments                  2.14.0             pyhd8ed1ab_0    conda-forge
pympler                   1.0.1              pyhd8ed1ab_0    conda-forge
pyopenssl                 23.1.1             pyhd8ed1ab_0    conda-forge
pyrsistent                0.19.3          py310h90acd4f_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.10.10         he7542f4_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-tzdata             2023.3             pyhd8ed1ab_0    conda-forge
python_abi                3.10                    3_cp310    conda-forge
pytz                      2023.3             pyhd8ed1ab_0    conda-forge
pytz-deprecation-shim     0.1.0.post0     py310h2ec42d9_3    conda-forge
pyyaml                    6.0             py310h90acd4f_5    conda-forge
pyzmq                     25.0.2          py310hf615a82_0    conda-forge
re2                       2023.02.02           hf0c8a7f_0    conda-forge
readline                  8.2                  h9e318b2_1    conda-forge
requests                  2.28.2             pyhd8ed1ab_1    conda-forge
ripgrep                   13.0.0               hbbacdb1_2    conda-forge
s3transfer                0.6.0              pyhd8ed1ab_0    conda-forge
setuptools                67.6.1             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
smmap                     3.0.5              pyh44b312d_0    conda-forge
snappy                    1.1.10               h225ccf5_0    conda-forge
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
streamlit                 1.2.0              pyhd8ed1ab_1    conda-forge
tabulate                  0.9.0              pyhd8ed1ab_1    conda-forge
tk                        8.6.12               h5dbffcc_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tornado                   6.2             py310h90acd4f_1    conda-forge
traitlets                 5.9.0              pyhd8ed1ab_0    conda-forge
trnascan-se               2.0.11          pl5321h1e3017b_0    bioconda
typing-extensions         4.5.0                hd8ed1ab_0    conda-forge
typing_extensions         4.5.0              pyha770c72_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
tzlocal                   4.3             py310h2ec42d9_0    conda-forge
urllib3                   1.26.15            pyhd8ed1ab_0    conda-forge
validators                0.20.0             pyhd8ed1ab_0    conda-forge
watchdog                  3.0.0           py310h389cd99_0    conda-forge
wcwidth                   0.2.6              pyhd8ed1ab_0    conda-forge
wget                      1.20.3               hd3787cc_1    conda-forge
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
widgetsnbextension        4.0.7              pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.9                h35c211d_0    conda-forge
xorg-libxdmcp             1.1.3                h35c211d_0    conda-forge
xz                        5.2.6                h775f41a_0    conda-forge
yaml                      0.2.5                h0d85af4_2    conda-forge
zeromq                    4.3.4                he49afe7_1    conda-forge
zipp                      3.15.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               hfd90126_4    conda-forge
zstd                      1.5.2                hbc0c0cd_6    conda-forge
```

**Comment by nh13** [comment]
Fixed here: https://github.com/bioconda/bioconda-recipes/pull/41445

**Comment by gasparitiago** [comment]
@nh13 Did some tests here and it seems to be working fine now :)

**Comment by mmcguffi** [comment]
This is (hopefully) more robustly fixed in https://github.com/mmcguffi/pLannotate/releases/tag/v1.2.1 (also on conda)

@nh13 I very much appreciate the fixes and pinning, but unfortunately I think it was a little to strict -- both on mac and linux conda/mamba was not able to solve the env

**Comment by simonvdalton** [comment]
Really enjoy these barrack lab updates. Keeps me connected to the barrick
family and an unexpected way (through my junk email no less).
