### ISSUE TITLE
`st.cache` is deprecated

### ISSUE THREAD

**Issue by bcantarel** [mmcguffi/pLannotate#39]
<jemalloc>: MADV_DONTNEED does not work (memset will be used instead)
<jemalloc>: (This is the expected behaviour if you are running under QEMU)
2024-01-28 22:23:41.053 
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run /opt/conda/bin/plannotate [ARGUMENTS]
2024-01-28 22:24:20.154 `st.cache` is deprecated. Please use one of Streamlit's new caching commands,
`st.cache_data` or `st.cache_resource`.

More information [in our docs](https://docs.streamlit.io/library/advanced-features/caching).
Traceback (most recent call last):
  File "/opt/conda/bin/plannotate", line 33, in <module>
    sys.exit(load_entry_point('plannotate==1.2.1', 'console_scripts', 'plannotate')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/plannotate/pLannotate.py", line 116, in main_batch
    recordDf = annotate(inSeq, yaml_file, linear, detailed)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/plannotate/annotate.py", line 355, in annotate
    blastDf = clean(blastDf)
              ^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/plannotate/annotate.py", line 178, in clean
    rowSlice = (seqSpace[columnSlice] == kind).any(1) #only the rows that are in the columns of hit
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DataFrame.any() takes 1 positional argument but 2 were given

**Comment by mmcguffi** [comment]
Hi @bcantarel I need more information to help you. How did you install pLannotate? What platform are you on? What commands did you use?

**Comment by bcantarel** [comment]
I used mamba like on the Readme:
mamba install plannotate

**Comment by mmcguffi** [comment]
Hi @bcantarel -- I was not able to replicate your issues manually, nor via automated tests: https://github.com/mmcguffi/pLannotate/actions

My best guess is that you are trying to install into an existing conda environment that already has conflicting tools -- I cannot guarantee that plannotate will work in these situations since I cannot test them. I suggest a fresh install as outlined in the readme:
```
mamba create -n plannotate -c conda-forge -c bioconda plannotate
```
